### PR TITLE
Manifest updates

### PR DESCRIPTION
**Pull request by triblondon**
* Change manifest version to 1

### CODE REVIEW

**Review by cratelyn — CHANGES_REQUESTED** [review]
:wave: Hi! I was a bit surprised to see the `[requires]` field showing up in our template manifests so soon.

So there's two things I have a bit of concern about here:

* First, we learned over in Viceroy that the CLI will actually panic when unexpected TOML fields are encountered in this manifest. I may have missed it, but has the CLI been patched (and released) to introduce these fields in its understanding of the schema?

* Second, I recall a meeting where we discussed this idea a bit, but I don't believe that we'd come to a conclusion about how these fields. I would really appreciate if we could specify this field more formally somewhere, i.e. a design doc, so that other tools that ingest this manifest can account for them properly.

**Comment by Integralist** [comment]
> we learned over in Viceroy that the CLI will actually panic when unexpected TOML fields are encountered in this manifest

Oh really. Would be worth us taking a look into that. I wouldn't have expected that. More that the cli would ignore fields it didn't recognise.

**Comment by cratelyn** [comment]
Gah! My apologies, slightly misspoke. IIRC the problem was that unrecognized fields were removed rather than causing a panic. I'll send you a link to relevant issue that described this.

**Comment by triblondon** [comment]
Hi @cratelyn - I am struggling a bit with what the right forum is for this, and whether that forum wants to talk about the whole spec or just individual parts of it.  I did a bit of a reset and tried to approach this by talking to people separately about their individual pieces of the puzzle, and the `[requires]` thing is something we came up with in devrel since we own the CLI and the SKs.  The idea is that the CLI will strip this data when it processes the SK's fastly.toml file, so it won't persist beyond the `compute init` task - so we're setting the scope fairly narrowly.

The full proposal for the fastly.toml reference is here https://github.com/fastly/Developer-Portal/pull/538 and I'd love to get feedback on that - including what more we should do here before we can merge it.  I'll add it to the ECP/devrel sync agenda for this week.

**Comment by cratelyn** [comment]
Thank you for the clarification @triblondon! That proposal is super helpful in understanding this, I hadn't seen this PR yet! Given that and the scoping information you laid out above, I feel much more comfortable about this.

The only quibble I have is that, going off of the proposal, this should be `[setup]` rather than `[requires]`; other than that I'm happy with this. :slightly_smiling_face: Once that's fixed, and the proposal has landed, I'm happy with this merging :rocket:

**Review by cratelyn — APPROVED** [review]

**Comment by triblondon** [comment]
After all that we ended up removing the `[requires]` section :-)

**Review by kailan — APPROVED** [review]

**Pull request merged**
